name: Deploy to GCE

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to GCE
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
          cd ~/randomyossy || git clone https://github.com/<あなたのGitHubユーザー名>/randomyossy.git
          cd ~/randomyossy
          git pull
          npm install
          pm2 restart yoshito-bot || pm2 start apexrpc.js --name yoshito-bot
          pm2 save
        EOF
